# Generated by Django 4.2.2 on 2023-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
    ]
